# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY helloworld.webapp/package*.json ./ 
#COPY helloworld.webapp/. .

RUN npm install --save-dev typescript react-scripts@3.0.1 

EXPOSE 3000

CMD ["npm", "start"]
